import { Card } from "@/components/ui/card";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { BookOpen } from "lucide-react";

export const Glossary = () => {
  const terms = [
    {
      term: "WAU (Weekly Active Users)",
      definition: "Unique users who either create or listen to mood mixes in any 7-day period. This metric measures behavioral change and shows genuine feature engagement."
    },
    {
      term: "eCPM (Effective Cost Per Mille)",
      definition: "Revenue earned per 1,000 ad impressions. Used to calculate advertising revenue for free tier users."
    },
    {
      term: "Feature Activation Rate",
      definition: "Percentage of users who create their first mood mix within 48 hours of discovering the feature. A key indicator of feature accessibility and user interest."
    },
    {
      term: "Mix Completion Rate",
      definition: "Percentage of mixes where users listen to at least half the tracks. Indicates recommendation quality and user satisfaction."
    },
    {
      term: "Retention Rate",
      definition: "Percentage of users who return to use the feature after their first interaction. Measured at 7-day and 30-day intervals to assess habit formation."
    },
    {
      term: "Listening Time Lift",
      definition: "Additional listening time generated by Mood Mix users compared to non-users. Target is +20% more weekly listening minutes."
    },
    {
      term: "WAU Penetration Rate",
      definition: "Mood Mix WAU as a percentage of total Spotify WAU. Shows product-market fit at scale, with targets of 20-25% by month 6."
    },
    {
      term: "Create-to-Listen Ratio",
      definition: "The ratio of mix creators to total listeners. Healthy range is 1:3 to 1:5, indicating mixes are being replayed and shared."
    },
    {
      term: "Churn Rate",
      definition: "Percentage of users who stop using Spotify over a given period. Mood Mix aims to reduce churn by increasing engagement and platform stickiness."
    },
    {
      term: "Leading Indicators",
      definition: "Metrics that predict future performance, such as activation rates and repeat usage. These provide early warning signals for course correction."
    },
    {
      term: "Lagging Indicators",
      definition: "Metrics that confirm long-term value, such as retention rates and revenue impact. These validate that the feature is meeting business objectives."
    }
  ];

  return (
    <section className="py-20 bg-secondary/20">
      <div className="container mx-auto px-6">
        <div className="max-w-4xl mx-auto">
          {/* Section Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 mb-4">
              <BookOpen className="w-6 h-6 text-primary" />
              <h2 className="text-4xl md:text-5xl font-bold">
                <span className="text-primary">Glossary</span> of Terms
              </h2>
            </div>
            <p className="text-lg text-muted-foreground">
              Key metrics and terminology used throughout this case study
            </p>
          </div>

          {/* Glossary Accordion */}
          <Card className="p-6 bg-card border-border">
            <Accordion type="single" collapsible className="w-full">
              {terms.map((item, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-left hover:text-primary transition-colors">
                    <span className="font-semibold">{item.term}</span>
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground leading-relaxed">
                    {item.definition}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </Card>
        </div>
      </div>
    </section>
  );
};
